[project]
name = "job-recomadation-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "apify-client>=2.5.0",
    "groq>=1.0.0",
    "pandas>=2.3.3",
    "pymupdf>=1.27.1",
    "streamlit>=1.54.0",
]
